### ISSUE TITLE
[Task] Upgrading to Uno Platform 5

### ISSUE THREAD

**Issue by al-kau** [Eppie-io/Eppie-App#296]
### Description

The application must use Uno Platform version 5.3 and run on the following platforms:
- Android
- iOS
- Web (WASM)
- macOS (Catalyst, Desktop)
- Linux (Desktop)
- Windows(WinUI, UWP, Desktop)

### Subtasks

- [x] #321
- [x] #323
- [x] #326
- [ ] #331
- [ ] Set up errors and warnings
- [ ] Set up code analyzers
- [ ] #332
- [ ] #330
- [x] #344
- [x] #347
- [ ] #382
- [ ] #384
- [ ] #500 
- [x] #358
- [x] Run UWP project
- [ ] #377
- [x] #327
- [x] #328
- [x] #298

### Additional Context

- [Upgrading to Uno Platform 5.0](https://platform.uno/docs/articles/migrating-to-uno-5.html)
- [Upgrading from previous releases](https://platform.uno/docs/articles/migrating-from-previous-releases.html)
- [Uno Publishing](https://platform.uno/docs/articles/uno-publishing-overview.html)

**Comment by al-kau** [comment]
- Task #677 is created for the new version of [Uno platform 6.0](https://platform.uno/blog/uno-platform-studio-6-0)
- Task #678 is created for unfinished subtasks
