### ISSUE TITLE
[Task] GitHub templates

### ISSUE THREAD

**Issue by al-kau** [Eppie-io/Eppie-App#303]
### Description

Configure and standardize the information that contributors must include when opening issues and pull requests in the repository.

### Subtasks

- [ ] **Bug report** template
- [ ] **New feature** template
- [ ] **Pull request** template
- [ ] **Release notes** template
