### ISSUE TITLE
[Task] Update Uno

### ISSUE THREAD

**Issue by al-kau** [Eppie-io/Eppie-App#432]
### Description

Update Uno projects.

### Subtasks

- [x] Update **Uno.Sdk** to 5.5.*
- [x] Update Uno projects to **net9.0**
- [x] Modify dotnet version in github actions
- [x] Update nugets

### Additional Information

[Migrating from Previous Releases of Uno Platform](https://platform.uno/docs/articles/migrating-from-previous-releases.html#uno-platform-55)
[Uno Platform 5.5](https://platform.uno/blog/5-5/)

**Comment by al-kau** [comment]
Done. Next update in task #505
